### ISSUE TITLE
User Logins - Page Optimization under Subscribers

### ISSUE THREAD

**Issue by nichuf** [davidfekke/lcorner#22]
Title - Lets Optimize your website

Do you rent space from any Storefronts?  
Drop down box of all Sponsors currently part of local corners.  One option in the drop down box will be I do not see them

Do yo rent booths from any reoccuring events?
Drop down box of all events currently subscribing to local corners.  One option in the drop down box will be I do not see my event

If we do not have the sponsor or event we will ask for them to supply the name and contact information.

**Comment by davidfekke** [comment]
I do not understand which page I am updating here.

**Comment by davidfekke** [comment]
For the wireframe, I am going to add an extra page to show what will happen once the user has selected the pictures. They will be given an option to "Optimize their page" with a list of sponsors, and checkboxes next to the sponsors.
