### ISSUE TITLE
Splash Screen when a Customer goes to LocalCorners.com

### ISSUE THREAD

**Issue by nichuf** [davidfekke/lcorner#23]
Splash Screen 
LocalCorners
Sign Up for free exclusive membership
Email address and zipcode - use facebook

Membership allows you to write reviews about your experience with a local

**Comment by davidfekke** [comment]
I think this go on a unified login/signup page.

**Comment by davidfekke** [comment]
This will be a modal to make sure people are logged in before they can proceed through the site.

This will be for a later phase.
