### ISSUE TITLE
Admin screen

### ISSUE THREAD

**Issue by nichuf** [davidfekke/lcorner#24]
The following are topics for us to be able to click on.  These topics are categories are basically notifications to the admin team.  It can consist of IT issues, notifcations for when subscribers are trying to optimize their site and the even or sponsor is not listed because they are not part of local corners yet

IT issues
Notifications
 A) lead generation
 B) new subscription
 C) Business Card Request - Autoconfirmation FTP was sent to Cherokee Print

**Comment by davidfekke** [comment]
Added this to the Admin page.
