### ISSUE TITLE
Customer Tab - enhancement

### ISSUE THREAD

**Issue by nichuf** [davidfekke/lcorner#36]
Adjacent to the "Want to join a corner button please add another button

"What is Local Corners
User will click on this button which will take them to a new page
On this new page add a description box.  This is where we will tell the story on how it was created and what the mission is.
Under the description are 2 buttons
"Want to Join a local corner which will follow the "What to Join a Corner" workflow
The second button "continue shopping which will redirect them back to the customer page.

**Comment by davidfekke** [comment]
Want to join a corner will stay on left.

**Comment by nichuf** [comment]
Completed after review
