### ISSUE TITLE
Picture samples

### ISSUE THREAD

**Issue by nichuf** [davidfekke/lcorner#41]
![img_0847 3](https://cloud.githubusercontent.com/assets/18232137/16545720/b0712fe8-4101-11e6-8191-9a92e5574ab2.JPG)
![img_4849](https://cloud.githubusercontent.com/assets/18232137/16545721/b073634e-4101-11e6-8f32-1080703c6aba.JPG)
![img_4862 1](https://cloud.githubusercontent.com/assets/18232137/16545719/b06ff10a-4101-11e6-8d50-9166516db738.JPG)

**Comment by davidfekke** [comment]
![jewelwry-ring](https://cloud.githubusercontent.com/assets/916406/16545971/ba2b7a14-4108-11e6-9f34-f7add4e2f488.jpg)
![scj-jewelry](https://cloud.githubusercontent.com/assets/916406/16545969/ba27d1a2-4108-11e6-9592-6d152b9534cc.jpg)
![tabletop](https://cloud.githubusercontent.com/assets/916406/16545970/ba29bd28-4108-11e6-9305-9f2be8916197.jpg)

**Comment by dylannirvana** [comment]
Gorgeous.
