### ISSUE TITLE
Local Corners Logo

### ISSUE THREAD

**Issue by nichuf** [davidfekke/lcorner#47]
Right now I have no idea where the logo should be inserted on the landing page but thought you might be able to play around with the location etc
![stamplogofontfixmh3green](https://cloud.githubusercontent.com/assets/18232137/24072483/ef234b7c-0bbd-11e7-879d-b6434aed9261.jpg)

**Comment by meghanhuff** [comment]
Hi David,
Just a heads up, that's not the correct logo Nick sent. Similar in shape though. I'll forward the right one shortly.
Thanks,

Meghan Huff

**Comment by meghanhuff** [comment]
Hi David,
Attached is the final logo.  I have multiple sizes if you need a smaller
version, however you should be able to manipulate as needed.  Pantone color
is 341c.  Please let me know if you have any issues.
Thanks,
Meghan
