### ISSUE TITLE
About Local Corners

### ISSUE THREAD

**Issue by nichuf** [davidfekke/lcorner#50]
When someone clicks on "About Local Corners"  It should take them to a page with the following
About Local Corners
We believe people want to support their local communities, talk to the person who grew their produce, learn what inspired the local artist to create their works, but most importantly they want to shake the hand of the person who created the product they purchased.  The problem is the producer and customer can’t find each other. 
Why?
The reasons are simple: Limited marketing and internet budgets and lack of brick and mortar store fronts. The small business can’t compete against the massive advertising dollars of large corporations.  The result.  One of a kind works, locally grown produce, stop at great ideas.  Perform some internet searches on anything in your city.  In all likelihood the results on the first page are dedicated to mass corporations
If you can’t be found within your local community, how can anyone expect to grow? That’s where Local Corners comes into help.
How Local Corners Works
Subscribers are the individuals who need help marketing their business.  We help subscribers create their own microsite on Local Corners and advertise for them.

Sponsors rental space to subscribers.  Think of arts and farmers markets and brick and mortar locations focusing on specific niches.  We help sponsors create a microsite on Local Corners and advertise for them as well.  Oftentimes, our subscribers also have relationships with our Sponsors.  The result is increased advertising for both!

**Comment by davidfekke** [comment]
I am closing this issue, and reopening in the correct repo.
[About Local Corners](https://github.com/davidfekke/localcorners/issues/1)
