### ISSUE TITLE
Main Local Corners Layout

### ISSUE THREAD

**Issue by nichuf** [davidfekke/lcorner#51]
I really like this layout

http://www.css-templates.org/detail/#tmpl_id=62439&url_preview=https://theme299-spare-parts.myshopify.com

Everything below the 9 categories (AKA the BMW below) omit.  Let me know if this makes sense

**Comment by davidfekke** [comment]
Do you want to use this on the landing page, or on the subscriber's page?

**Comment by davidfekke** [comment]
I am closing this issue, and reopening in the correct repository.

[Layout idea](https://github.com/davidfekke/localcorners/issues/2)

**Comment by nichuf** [comment]
The layout would be for the landing page. The nine boxes you see below will be specific types of local corners. Examples would be "refinished row" "furniture blvd" "farmers court" etc. 

The main illustrated box at the top will be where the logo will be. In the background will  various pictures in rotation of markets, people actually making their works, etc.  similar to the CSs template I sent this area will have a button that will say about local corners.
the menu bar will have login, search, contact us,

Let me know if that makes sense. I can do a mock up if you would like.
