### ISSUE TITLE
Profile Picture Gallary - Description

### ISSUE THREAD

**Issue by nichuf** [davidfekke/lcorner#53]
We discussed adding the description field on the right hand side of the subscribers photo gallary.  As the subscriber clicks on their pictures the description on the right hand side will change according to the the picture they have selected.  It is then the subscriber will be able to modify their descriptions.  

We also discussed adding a keyword section they can use to enhance search capabilities

**Comment by davidfekke** [comment]
I believe this has been completed. Please verify.
