### ISSUE TITLE
After Clicking the Join Button

### ISSUE THREAD

**Issue by nichuf** [davidfekke/lcorner#58]
I noticed when I clicked on the Join button it took me to the screen 'Register for Local Corners"
It appears because of cookies it retains my email address.   This probably should not happen.
[Register for Local Corners.docx](https://github.com/davidfekke/lcorner/files/1367060/Register.for.Local.Corners.docx)

**Comment by davidfekke** [comment]
That is not a cookie. That is functionality of the browser. I am closing this issue.
