### ISSUE TITLE
Registered as Huck Huff

### ISSUE THREAD

**Issue by nichuf** [davidfekke/lcorner#59]
After Registering as Huck Huff, I recieved the message" You are Registered and can now login.  When I did this though it defaulted to nick.huff@localcorners.com
[After Creating a new registration.docx](https://github.com/davidfekke/lcorner/files/1367063/After.Creating.a.new.registration.docx)

Once I removed nick.huff@localcorners.com I then changed it to Huck.huff@gmail.com and supplied the password.  That worked.

**Comment by nichuf** [comment]
Need to prevent it from defaulting

**Comment by davidfekke** [comment]
This is functionality of the browser, not the site. I am leaving open until we can discuss.
