### ISSUE TITLE
Customer Landing Page

### ISSUE THREAD

**Issue by nichuf** [davidfekke/lcorner#6]
Please add the following tiles.  The tiles should be square similar to the apps on your iphone.  The following tiles are 
Handmade BLVD
Refinished Row
Artist AVE
Farmers CT
Events PKWY
Restaruant Way
Music...
Apparel Lane
Make a Day

3x3
Under the tiles add a button "Want to join a corner?"

**Comment by davidfekke** [comment]
Added a new customers landing page.
