### ISSUE TITLE
Subscriber Profile - Uploaded Pictures - Unable to Crop

### ISSUE THREAD

**Issue by nichuf** [davidfekke/lcorner#64]
Using the profile
huck.huff@gmail.com
njh041279

I uploaded 2 pictures. After the upload the only way to be able to crop the pictures was to exit the upload window go back into the profile, click subsciber profile

As the upload occurs the ability to crop and modify should occur immediately

**Comment by davidfekke** [comment]
This is how it will have to work if we are going to allow the users to upload multiple images at the same time. I am closing.
