### ISSUE TITLE
Cropping Tool - Issue???

### ISSUE THREAD

**Issue by nichuf** [davidfekke/lcorner#65]
One of the things I noticed about the cropping tool is it will not allow my to rotate a picture I upload.  The sizing seems to be working well but am positive people will upload pictures only to have them be upside down.  If they can't rotate on on site they will get frustrated

**Comment by davidfekke** [comment]
We need to discuss how you want them to rotate the images. It gets complicated if you do not rotate in 90 degree increments.

**Comment by davidfekke** [comment]
Images are rotating on different angles depending on the view. Take a look and see if we can override, and add rotate button.

**Comment by nichuf** [comment]
I took 3 images and stored them upside down, sideways and right ways (however) it is said and was able to crop accordingly
