### ISSUE TITLE
Picture - Title and Description...How should we categorize

### ISSUE THREAD

**Issue by nichuf** [davidfekke/lcorner#66]
One of the things I noticed when adding title and description is the subscriber and sponsor don't have a way to categorize their works.  This is important because we don't want a farmer with a bunch of veg for sale having all their pictures in the jewelry section

You have any thoughts on this?  Should we have a section for them to choose the category under the description section?

**Comment by davidfekke** [comment]
Lets discuss

**Comment by davidfekke** [comment]
Looks like this completed
